### PR TITLE
Fix creating and building example and cleanup code around it

### LINKED ISSUE #69: Add postinstall removing of example
Using the newest version from master with automatically generated example I faced a problem when I ran `react-native start`  with duplication of dependencies. 
`example` folder is being copied while installing `example`  (because of `file:../` dependency). The solution is imo to add some postinstall script (like [here](https://github.com/osdnk/react-native-haptics/blob/f4a859fd1ca26f99904415166ba8b9ae45bf9807/example/package.json#L8) I have done) :)

### PR DESCRIPTION
**Pull request by maicki**
This PR fixes running examples within libraries which didn't work before as the metro bundler was confused of multiple modules. The reason for that is that if we link the library via `library-name: file:..` within the `package.json` of the example the `node_modules` folder of this library get's copied too what causes a multiple modules error at the end if react native tries to run.

This PR is adding a script to the library and executes it after running `npm / yarn install` within the example. The script looks into the `node_modules` folder of the example for the library and removes the `node_modules` within that libraries folder.

Fixes #69

### CODE REVIEW

File: templates/example.js [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+
+let templates = []
+
+module.exports = [{
+  name: () => 'scripts/examples_postinstall.js',
+  content: () =>
+`#!/usr/bin/env node
+
+  /*
+   * Using libraries within examples and linking them within packages.json like:
```
Comment (thorbenprimke) [inline templates/example.js]: The juicy stuff!

File: lib.js [hunk 2]
```diff
@@ -88,29 +89,52 @@ module.exports = ({
...
+            })
+          );
+        })
+        .then(() => {
+          // Adds and link the new library
+          return new Promise((resolve, reject) => {
+            // Add postinstall script to example package.json
+            const pathExampleApp = `./${name}/example`;
+            const moduleName = `${modulePrefix}-${paramCase(name)}`;
+            npmAddScriptSync(`${pathExampleApp}/package.json`, {
```
Comment (thorbenprimke) [inline lib.js]: nice

File: lib.js [hunk 3]
```diff
@@ -88,29 +89,52 @@ module.exports = ({
...
+              value: `node ../scripts/examples_postinstall.js node_modules/${moduleName}`
+            });
+
+            // Add and link the new library
+            const addLinkLibraryOptions = { cwd: pathExampleApp, stdio: 'inherit' };
+            try {
+              execSync('yarn add file:../', addLinkLibraryOptions);
+            } catch (e) {
+              execSync('npm install ../', addLinkLibraryOptions);
+              execSync('npm install', addLinkLibraryOptions);
```
Comment (thorbenprimke) [inline lib.js]: Did you mean to leave this one in here?

Comment (maicki) [reply lib.js]: I didn't know why it was in there in the first place. Look on the left side except renaming the options variable the logic didn't change. Do you recall why we have that in there twice?
